version: 0.2

phases:
  build:
    commands:
      - echo Build phase for COMPILER started at $(date)
      - echo The current directory is ...
      - export CODEDIR=$(pwd)
      - ls -la
      - cd application ; ls -la
      - FILENAME="time_exchange-$(date +'%d%m%Y%H%M').zip" 
      - zip ../artifacts/${FILENAME} time_exchange.py
      - echo ${FILENAME} >> ../artifacts/list.yml
  post_build:
    commands:
      - echo Post build completed on $(date)
      - cd .. ; ls -la artifacts/
artifacts:
  files:
    - '**/*'
  name: compiled_code
